dynamic_parameters:
  g: 9.81
  M: 1.0 # mass of the cart
  m: 0.3 # mass of the pole
  l: 0.5 # length of the pole
  h: 0.05 # sec, sampling time for the discrited euler dynamics

DDP:
  T: 5.0 # total time horizon for the trajectory
  Qk: 10.0 # lagrange cost weight for state x
  QN: 1000.0 # terminal cost weight for state x
  R: 0.01 # cost weight for control force
  max_iter: 100 # maximum iteration
  use_hessian: 0 # use full DDP or iLQR
