dynamic_parameters:
  g: 9.81
  M: 1.0 # mass of the cart
  m: 0.3 # mass of the pole
  l: 0.5 # length of the pole

DDP:
  Nt: 100 # number of discreted trajectory points
  T: 2.0 # total time horizon for the trajectory
  Qk: 1.0 # lagrange cost weight for state x
  QN: 2.0 # terminal cost weight for state x
  R: 0.1 # cost weight for control force

